name: On push master castro_weather.py

on:
    push:
      branches:
        - master

jobs:
  fetch_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          STATION_ID: ${{ secrets.STATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python castro_weather.py