name: Weather Data Fetch
on:
  schedule:
    - cron: '00 15 * * *'  # Ejecuta todos los días a las 00:00 UTC

jobs:
  fetch_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          STATION_ID: ${{ secrets.STATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python castro_wheather.py "$STATION_ID" "$API_KEY"
