name: run castro_wheather.py at 15h 

on:
  schedule:
    - cron: '00 15 * * *'  # Running at 15:00 UTC every days.

jobs:
  fetch_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          STATION_ID: ${{ secrets.STATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python castro_wheather.py "$STATION_ID" "$API_KEY"
